baseURL = "https://gorgonia.org/"
languageCode = "en-us"
title = "Gorgonia - Deep Learning Library for Go"
publishDir = "../docs"
theme = "hugo-material-docs"
canonifyurls = true


[params]
	# General information
	author = "Gorgonia Authors"
	description = "Gorgonia is a suite of libraries for creating performant deep learning and machine learning applications in Go"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/gorgonia"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
		primary = "light-blue"
		accent  = "deep-orange"

	[params.font]
		text = "Roboto"
		code = "Roboto Mono"


[social]
	twitter = "gorgonia"
	github  = "gorgonia"


[[menu.main]]
	name   = "Home"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Gorgonia"
	url    = "gorgonia/"
	weight = 10

[[menu.main]]
	name   = "Tensor"
	url    = "tensor/"
	weight = 20

[[menu.main]]
	name = "Golgi"
	url = "golgi/"
	weight = 30

[[menu.main]]
	name   = "CUDA"
	url    = "cu/"
	weight = 40

[[menu.main]]
	name   = "RandomKit"
	url    = "randomkit/"
	weight = 50

[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 60

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 60


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
plainIDAnchors = true