title: Gorgonia
lang: en
email: hello@gorgonia.com
url: 'https://tiste.github.io'
twitter:
  username: gorgonia
  card: summary
github_username: gorgonia
social:
  name: Gorgonia
  links:
    - https://twitter.com/gorgonia
    - https://github.com/gorgonia
logo: /brand.png

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
